### ISSUE TITLE
TypeError: Argument 1 passed to {closure}() must be an instance of Blueprint

### ISSUE THREAD

**Issue by willdashwood** [openprovider/OP-WHMCS7#14]
When activating the OpenProvider domain addon I get the following error:

```
TypeError: Argument 1 passed to {closure}() must be an instance of Blueprint, instance of Illuminate\Database\Schema\Blueprint given, called in /home/nginx/domains/OURDOMAIN.COM/public/billing/vendor/illuminate/database/Schema/Blueprint.php on line 69 and defined in /home/nginx/domains/OURDOMAIN.COM/public/billing/modules/addons/openprovider/openprovider.php:64
Stack trace:
#0 /home/nginx/domains/OURDOMAIN.COM/public/billing/vendor/illuminate/database/Schema/Blueprint.php(69): {closure}(Object(Illuminate\Database\Schema\Blueprint))
#1 /home/nginx/domains/OURDOMAIN.COM/public/billing/vendor/illuminate/database/Schema/Builder.php(245): Illuminate\Database\Schema\Blueprint->__construct('tblinvoiceitems', Object(Closure))
#2 /home/nginx/domains/OURDOMAIN.COM/public/billing/vendor/illuminate/database/Schema/Builder.php(130): Illuminate\Database\Schema\Builder->createBlueprint('tblinvoiceitems', Object(Closure))
#3 /home/nginx/domains/OURDOMAIN.COM/public/billing/modules/addons/openprovider/openprovider.php(66): Illuminate\Database\Schema\Builder->table('tblinvoiceitems', Object(Closure))
#4 /home/nginx/domains/OURDOMAIN.COM/public/billing/whmcsadmin/configaddonmods.php(0): openprovider_activate()
#5 {main}
```

**Comment by wmetge** [comment]
@willdashwood thank you for brining this to our attention. The issue has been fixed in commit 27c0be67ea1640ee8a631154a24763514f0f4392
