### ISSUE TITLE
Addons module results in status 500

### ISSUE THREAD

**Issue by ovvessem** [openprovider/OP-WHMCS7#18]
When trying to access the openprovider addons module from the WHMCS backend it results in a 500 error with the following error log message:

[domain] references full_path and domain name.

```
mod_fcgid: stderr: [WHMCS Application] ERROR: Error: Function name must be a string in [domain]/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php:91 
Stack trace: 
#0 [domain]/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/AdminDispatcher.php(26): WeDevelopCoffee\\wPower\\Controllers\\Dispatcher->dispatch('index', Array) 
#1 [domain]/modules/addons/openprovider/openprovider.php(48): WeDevelopCoffee\\wPower\\Controllers\\AdminDispatcher->dispatch('', Array) 
#2 [domain]/boss/addonmodules.php(0): openprovider_output(Array) 
#3 {main} {"exception":"[object] (Error(code: 0): Function name must be a string at [domain]/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php:91)"} [], referer: [domain]/addonmodules.php
```

**Comment by ovvessem** [comment]
Commit https://github.com/openprovider/OP-WHMCS7/commit/77c7057c7289b5cfbc4c56db2795a05d57877fda resolved this issue.
