### ISSUE TITLE
Opening addonmodule - couldn't process your request

### ISSUE THREAD

**Issue by Nossie** [openprovider/OP-WHMCS7#19]
uri : /addonmodules.php?module=openprovider

> Oops!
> Something went wrong and we couldn't process your request.
> Please go back to the previous page and try again.

```
Exception: NOT FOUND in /var/www/html/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php:130
Stack trace:
#0 /var/www/html/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php(85): WeDevelopCoffee\wPower\Controllers\Dispatcher->getControllerNameAndFunction()
#1 /var/www/html/billing/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/AdminDispatcher.php(26): WeDevelopCoffee\wPower\Controllers\Dispatcher->dispatch('index', Array)
#2 /var/www/html/billing/modules/addons/openprovider/openprovider.php(48): WeDevelopCoffee\wPower\Controllers\AdminDispatcher->dispatch('', Array)
#3 /var/www/html/billing/WH/addonmodules.php(0): openprovider_output(Array)
#4 {main}
```

**Comment by ovvessem** [comment]
Commit https://github.com/openprovider/OP-WHMCS7/commit/77c7057c7289b5cfbc4c56db2795a05d57877fda resolves this issue.

**Comment by wmetge** [comment]
@Nossie and @ovvessem , thank you for your feedback.
