### ISSUE TITLE
Error when try module

### ISSUE THREAD

**Issue by hostingwalk** [openprovider/OP-WHMCS7#30]
I have installed the module, but when try to run, is show the below errors:

```
Error: Function name must be a string in /modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/Dispatcher.php:91
Stack trace:
#0modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Controllers/AdminDispatcher.php(26): WeDevelopCoffee\wPower\Controllers\Dispatcher->dispatch('index', Array)
#1 /modules/addons/openprovider/openprovider.php(48): WeDevelopCoffee\wPower\Controllers\AdminDispatcher->dispatch('', Array)
#2 /addonmodules.php(0): openprovider_output(Array)
#3 {main}
```

**Comment by soberoctober** [comment]
hi @hostingwalk 
the addon calculator is a product of a third-party development and soon will be removed from this repository because of its inconsistent UX amongst our user base.
we can refer you to the developer of that module in case you absolutely need it.
