### ISSUE TITLE
Parse Error: cron.php do --DomainTransferSync

### ISSUE THREAD

**Issue by willdashwood** [openprovider/OP-WHMCS7#82]
Just upgraded to latest master release and I'm getting the following error when running cron.php do --DomainTransferSync

```
[WHMCS Application] ERROR: ParseError: syntax error, unexpected ')', expecting ';' in /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/Controllers/System/TransferSyncController.php:78 Stack trace: #0 /home/nginx/domains/domain.com/public/billing/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/nginx/dom...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('OpenProvider\\Wh...') #2 [internal function]: spl_autoload_call('OpenProvider\\Wh...') #3 /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(30): class_exists('\\OpenProvider\\W...') #4 /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(52): WeDevelopCoffee\wPower\Core\Instance->createInstance('TransferSyncCon...') #5 /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/openprovider.php(270): WeDevelopCoffee\wPower\Core\Launch->output(Array, 'transferSync') #6 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Task/DomainTransferSync.php(0): openprovider_TransferSync(Array) #7 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\DomainTransferSync->__invoke() #8 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute() #9 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run() #10 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection)) #11 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\DoCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /home/nginx/domains/domain.com/whmcsdata/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 {main} {"exception":"[object] (ParseError(code: 0): syntax error, unexpected ')', expecting ';' at /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/Controllers/System/TransferSyncController.php:78)"} []
ParseError: syntax error, unexpected ')', expecting ';' in /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/Controllers/System/TransferSyncController.php:78
```

The thing I can't quite understand is that I don't get that same error on another WHMCS installation that has also been upgraded to latest release. Perhaps it's because the file in question (TransferSyncController.php) isn't being called yet. Anyone else have this issue?

**Comment by MrKoopie** [comment]
@willdashwood Sounds like a corrupted upload. Can you make sure that the file is not corrupted, if so, post the contents of /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/Controllers/System/TransferSyncController.php here?

**Comment by willdashwood** [comment]
Already downloaded the zip file several times and compared the file to the one I have operating on the other WHMCS installation. It's identical. So I'm a bit puzzled.
[TransferSyncController.php,.txt](https://github.com/openprovider/OP-WHMCS7/files/4603311/TransferSyncController.php.txt)

**Comment by MrKoopie** [comment]
Can you try to implement https://github.com/openprovider/OP-WHMCS7/pull/84 ? There is indeed a typo here.
