### ISSUE TITLE
'OpenProvider\WhmcsRegistrar\Controllers\System\Carbon' not found

### ISSUE THREAD

**Issue by willdashwood** [openprovider/OP-WHMCS7#89]
Over the weekend, suddenly started getting the follow errors from cron despite not touching anything (no one with access to this server was working Saturday).

```
[WHMCS Application] ERROR: Error: Class 'OpenProvider\WhmcsRegistrar\Controllers\System\Carbon' not found in /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/Controllers/System/TransferSyncController.php:77 Stack trace: #0 /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\TransferSyncController->sync(Array) #1 /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute('sync', Array) #2 /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/openprovider.php(270): WeDevelopCoffee\wPower\Core\Launch->output(Array, 'transferSync') #3 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Task/DomainTransferSync.php(0): openprovider_TransferSync(Array) #4 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\DomainTransferSync->__invoke() #5 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute() #6 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run() #7 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection)) #8 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\DoCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /home/nginx/domains/domain.com/whmcsdata/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 {main} {"exception":"[object] (Error(code: 0): Class 'OpenProvider\\WhmcsRegistrar\\Controllers\\System\\Carbon' not found at /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/Controllers/System/TransferSyncController.php:77)"} []
Error: Class 'OpenProvider\WhmcsRegistrar\Controllers\System\Carbon' not found in /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/Controllers/System/TransferSyncController.php:77

#0 /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\TransferSyncController->sync(Array)
#1 /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute('sync', Array)
#2 /home/nginx/domains/domain.com/public/billing/modules/registrars/openprovider/openprovider.php(270): WeDevelopCoffee\wPower\Core\Launch->output(Array, 'transferSync')
#3 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Task/DomainTransferSync.php(0): openprovider_TransferSync(Array)
#4 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\DomainTransferSync->__invoke()
#5 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute()
#6 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run()
#7 /home/nginx/domains/domain.com/public/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection))
#8 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\DoCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/nginx/domains/domain.com/public/billing/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/nginx/domains/domain.com/whmcsdata/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Absolutely baffled why this error suddenly occurred. I tried doing a fresh upgrade to latest master release but still no joy.

**Comment by willdashwood** [comment]
Any update on this? It's a fairly critical error.

**Comment by willdashwood** [comment]
Still no word on this? It's still happening. As soon as we have a domain name pending transfer with the plugin set to openprovider, we get this error on cron.

**Comment by kess78** [comment]
Exactly the same here. What I could see is that it happens when more than 1 domain transfers should be set to active during the same cron poll.

**Comment by willdashwood** [comment]
I'm seeing the error whenever there's 1 or more pending transfer domain assigned to openprovider plugin.

**Comment by soberoctober** [comment]
@willdashwood Carbon class wasn't initialised in the corresponding controller. Could you try with the latest commit please?

**Comment by willdashwood** [comment]
Yeah I saw the update last week, applied it immediately and seems to have solved the problem. Thanks

**Comment by lennarttd** [comment]
This issue is again present. Added a pull request to fix this issue.

**Comment by willdashwood** [comment]
Was this never committed to master branch? We upgraded to WHMCS 8.0.4 a week or so ago. At the same time I took the opportunity to upgrade the OpenProvider module as I hadn't done it in a while. I think I had been running the dev branch from ages ago.

**Comment by lennarttd** [comment]
It was but apparently got lost again. Please see my pull request to see how to solve this issue.

________________________________
Van: Will <notifications@github.com>
Verzonden: dinsdag, januari 5, 2021 6:25 PM
Aan: openprovider/OP-WHMCS7
CC: Lennart Dreves; Comment
Onderwerp: Re: [openprovider/OP-WHMCS7] 'OpenProvider\WhmcsRegistrar\Controllers\System\Carbon' not found (#89)


Was this never committed to master branch? We upgraded to WHMCS 8.0.4 a week or so ago. At the same time I took the opportunity to upgrade the OpenProvider module as I hadn't done it in a while. I think I had been running the dev branch from ages ago. Now I'm getting the original error again.

**Comment by willdashwood** [comment]
@lennarttd Thanks, just seen it. Unbelievable really!
